### PR TITLE
Squash Add() into one function

### PR DESCRIPTION
**Pull request by jerryct**

### CODE REVIEW

**Comment by bdangit** [comment]
Whoa this is a pretty big change in the interface.  When you tag the release, I’d recommend a major bump in the version.

**Comment by gjasny** [comment]
@bdangit I was thinking the same but it's in the `private` parts of Registry.

**Comment by bdangit** [comment]
Ah! Yes. You are right. :thumbsup: In any case, would love to have a version bump.  :)

**Comment by jupp0r** [comment]
it's in [v0.6.0](https://github.com/jupp0r/prometheus-cpp/releases/tag/v0.6.0)

**Pull request merged**
