### PR TITLE
CMake: Fix directory permissions on installation

### LINKED ISSUE #361: Directory permissions too restrictive in Debian (and probably) RPM packages for cmake folders.
The Debian package file generated by CMake/Cpack based on the instructions in the README.mb include some splurious and unneeded files in /usr/lib/cmake/. These should be removed from the install target list for the packages.
```
stephen.bates@bragi:~/prometheus-cpp$ dpkg -c _build/prometheus-cpp_0.9.0_amd64.deb 
drwxr-x--- root/root         0 2020-04-23 07:10 ./usr/
drwxr-xr-x root/root         0 2020-04-23 07:10 ./usr/include/
drwxr-xr-x root/root         0 2020-04-23 07:10 ./usr/include/prometheus/
-rw-r--r-- root/root       275 2020-04-23 07:09 ./usr/include/prometheus/check_names.h
-rw-r--r-- root/root      1363 2020-04-23 07:09 ./usr/include/prometheus/client_metric.h
-rw-r--r-- root/root       560 2020-04-23 07:09 ./usr/include/prometheus/collectable.h
-rw-r--r-- root/root      2498 2020-04-23 07:09 ./usr/include/prometheus/counter.h
drwxr-xr-x root/root         0 2020-04-23 07:10 ./usr/include/prometheus/detail/
-rw-r--r-- root/root       522 2020-04-23 07:09 ./usr/include/prometheus/detail/builder.h
-rw-r--r-- root/root      1069 2020-04-23 07:09 ./usr/include/prometheus/detail/ckms_quantiles.h
-rw-r--r-- root/root      1319 2020-04-23 07:10 ./usr/include/prometheus/detail/core_export.h
-rw-r--r-- root/root       339 2020-04-23 07:09 ./usr/include/prometheus/detail/future_std.h
-rw-r--r-- root/root      1319 2020-04-23 07:10 ./usr/include/prometheus/detail/pull_export.h
-rw-r--r-- root/root      1319 2020-04-23 07:10 ./usr/include/prometheus/detail/push_export.h
-rw-r--r-- root/root       860 2020-04-23 07:09 ./usr/include/prometheus/detail/time_window_quantiles.h
-rw-r--r-- root/root       489 2020-04-23 07:09 ./usr/include/prometheus/detail/utils.h
-rw-r--r-- root/root      1081 2020-04-23 07:09 ./usr/include/prometheus/exposer.h
-rw-r--r-- root/root      6098 2020-04-23 07:09 ./usr/include/prometheus/family.h
-rw-r--r-- root/root      1653 2020-04-23 07:09 ./usr/include/prometheus/gateway.h
-rw-r--r-- root/root      2749 2020-04-23 07:09 ./usr/include/prometheus/gauge.h
-rw-r--r-- root/root      3774 2020-04-23 07:09 ./usr/include/prometheus/histogram.h
-rw-r--r-- root/root       389 2020-04-23 07:09 ./usr/include/prometheus/metric_family.h
-rw-r--r-- root/root       148 2020-04-23 07:09 ./usr/include/prometheus/metric_type.h
-rw-r--r-- root/root      3111 2020-04-23 07:09 ./usr/include/prometheus/registry.h
-rw-r--r-- root/root       491 2020-04-23 07:09 ./usr/include/prometheus/serializer.h
-rw-r--r-- root/root      4985 2020-04-23 07:09 ./usr/include/prometheus/summary.h
-rw-r--r-- root/root       462 2020-04-23 07:09 ./usr/include/prometheus/text_serializer.h
drwxr-x--- root/root         0 2020-04-23 07:10 ./usr/lib/
drwxr-x--- root/root         0 2020-04-23 07:10 ./usr/lib/cmake/
drwxr-x--- root/root         0 2020-04-23 07:10 ./usr/lib/cmake/prometheus-cpp/
-rw-r--r-- root/root      1523 2020-04-23 07:10 ./usr/lib/cmake/prometheus-cpp/prometheus-cpp-config.cmake
-rw-r--r-- root/root      1931 2020-04-23 07:10 ./usr/lib/cmake/prometheus-cpp/prometheus-cpp-targets-noconfig.cmake
-rw-r--r-- root/root      4118 2020-04-23 07:10 ./usr/lib/cmake/prometheus-cpp/prometheus-cpp-targets.cmake
lrwxrwxrwx root/root         0 2020-04-23 07:10 ./usr/lib/libprometheus-cpp-core.so -> libprometheus-cpp-core.so.0.9
lrwxrwxrwx root/root         0 2020-04-23 07:10 ./usr/lib/libprometheus-cpp-core.so.0.9 -> libprometheus-cpp-core.so.0.9.0
-rw-r--r-- root/root   2252496 2020-04-23 07:10 ./usr/lib/libprometheus-cpp-core.so.0.9.0
lrwxrwxrwx root/root         0 2020-04-23 07:10 ./usr/lib/libprometheus-cpp-pull.so -> libprometheus-cpp-pull.so.0.9
lrwxrwxrwx root/root         0 2020-04-23 07:10 ./usr/lib/libprometheus-cpp-pull.so.0.9 -> libprometheus-cpp-pull.so.0.9.0
-rw-r--r-- root/root    555520 2020-04-23 07:10 ./usr/lib/libprometheus-cpp-pull.so.0.9.0
lrwxrwxrwx root/root         0 2020-04-23 07:10 ./usr/lib/libprometheus-cpp-push.so -> libprometheus-cpp-push.so.0.9
lrwxrwxrwx root/root         0 2020-04-23 07:10 ./usr/lib/libprometheus-cpp-push.so.0.9 -> libprometheus-cpp-push.so.0.9.0
-rw-r--r-- root/root    543560 2020-04-23 07:10 ./usr/lib/libprometheus-cpp-push.so.0.9.0
```

### PR DESCRIPTION
**Pull request by sbates130272**
This patch sets the default permission for installed directories as
755, using variable CMAKE_INSTALL_DEFAULT_DIRECTORY_PERMISSIONS, which
was introduced in CMake 3.11.

Note that not setting this variable leads to platform specific
behaviour which can change from user to user.

Fixes #361

### CODE REVIEW

**Comment by sbates130272** [comment]
I have no idea why that one CI test failed?

**Comment by gjasny** [comment]
Hello,
thank you for your analysis and pull request. I cannot easily reproduce the error on my end. In case the permission problem got fixed with a certain CMake version I'd like to annotate the setting of the variable with that information to be able to remove it at a later point in time.

What's your buidl environment?
* OS (name, version)
* CMake version
* umask

Thanks,
Gregor

**Comment by gjasny** [comment]
I spoke too soon. I can reproduce it and will have a look.

**Comment by gjasny** [comment]
This is due to https://gitlab.kitware.com/cmake/cmake/issues/15163

**Comment by sbates130272** [comment]
Thanks for merging @gjasny!

**Pull request merged**
